---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: drupal-cron
  namespace: drupal
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            image: byrnedo/alpine-curl:0.1.8
            args:
            - -s
            - https://ep6.kube101.jeffgeerling.com/en/cron/LPgIVauewMqWtsJhWzeMkp0_5EGkTZumJE4KA4Mf-nraXiap2j5zqc31aPbVjSIHRkRN74qGpg
          restartPolicy: OnFailure
