---
- name: Converge
  hosts: nfs
  become: true

  tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

- import_playbook: ../../main.yml
  vars:
    nfs_exports: []