---
name: Build Episodes

on:
  push:
    branches:
      - master

jobs:
  docker-image-builds:
    name: Docker image builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Episode 1.
          - episode: '01'
            dockerfile: Dockerfile
            repo: kube101
            tag: intro

          # Episode 2.
          - episode: '02'
            dockerfile: Dockerfile
            repo: kube101
            tag: hello-go
          - episode: '02'
            dockerfile: Dockerfile
            repo: kube101-go
            tag: '1.0.0'

          # Episode 3.
          - episode: '03'
            dockerfile: Dockerfile
            repo: kube101-go
            tag: '1.1.0'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./episode-${{ matrix.episode }}/
          file: ./episode-${{ matrix.episode }}/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: geerlingguy/${{ matrix.repo }}:${{ matrix.tag }}
