---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "40 5 * * 0"

jobs:
  hello-go:
    name: Hello Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"

      - name: Run hello Go app tests (Episode 2).
        run: go test
        working-directory: episode-02/cmd/hello

      - name: Run hello Go app tests (Episode 3).
        run: go test
        working-directory: episode-02/cmd/hello

  nfs-server:
    name: NFS Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint
        working-directory: episode-02/cmd/hello

      - name: Run Molecule tests.
        run: molecule test
        working-directory: episode-05/nfs-server
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
